FROM debian:trixie-slim

ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt update && apt upgrade -y \
  && apt install -y --no-install-recommends --no-install-suggests gnupg2 ca-certificates curl nginx openssl libcap2-bin \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# Allow non-root nginx to bind to privileged ports (80/443)
RUN setcap 'cap_net_bind_service=+ep' /usr/sbin/nginx

# Check Nginx version
RUN nginx -v

# Configure Nginx: Copy custom configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Create a custom non-root user
RUN groupadd -g 101 nginx \
  && useradd -u 1001 -g nginx -s /sbin/nologin -M nginx

RUN mkdir /etc/certs \
  && openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:4096 -keyout /etc/certs/privkey.pem -out /etc/certs/cert.pem -subj '/C=EU/ST=DE/L=example/O=graphql/CN=localhost'

# Copy application files
COPY app/ /var/www/html/

# Change ownership of Nginx directories
RUN mkdir -p /var/run/nginx \
  && touch /run/nginx.pid \
  && chown -R nginx:nginx /var/www /var/log/nginx /etc/certs /var/lib/nginx /var/run/nginx /run/nginx.pid

# Expose ports
EXPOSE 80 443

# Switch to non-root user
USER nginx

HEALTHCHECK --interval=35s --timeout=4s CMD curl --fail --insecure https://localhost:443/health || exit 1

# Default command to start
CMD ["nginx", "-g", "daemon off;"]
