FROM debian:trixie-slim

ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt update && apt upgrade -y \
  && apt install -y --no-install-recommends --no-install-suggests gnupg2 ca-certificates curl nginx openssl \
  && rm -rf "/var/lib/apt/lists/*" \
  && rm -rf /var/cache/apt/archives

# Check Nginx version
RUN nginx -v

# Configure Nginx: Copy custom configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Create a custom non-root user
RUN groupadd -g 101 nginx && \
    useradd -u 1001 -g nginx -s /sbin/nologin -M nginx

RUN mkdir /etc/certs \
  && openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/certs/privkey.pem -out /etc/certs/cert.pem

# Copy application files
COPY app/ /var/www/

# Change ownership of Nginx directories
RUN chown -R nginx:nginx /var/www /var/log/nginx /var/cache/nginx /etc/certs

# Expose ports
EXPOSE 80 443

# Switch to non-root user
USER nginx

# Default command to start
CMD ["nginx", "-g", "daemon off;"]
